version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/usr/src/app
      - nodemodules:/usr/src/app/node_modules
    ports:
      - 4000:4000
      - 9229:9229
    restart: always
    depends_on:
      - database
  database:
    build: ./database
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "supersecret"
      MYSQL_DATABASE: "benchmark"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "pass"
    volumes:
      - mysql-db:/var/lib/mysql
    restart: always

volumes:
  mysql-db:
  nodemodules:
